# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-18.04]

        fail-fast: false

    steps:

    - name: setup
      run: echo "::add-path::${HOME}/opt/conda/bin"

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: dependency (ubuntu)
      if: matrix.os != 'macos-latest'
      run: |
        sudo apt-get -q update
        sudo apt-get -qy install \
            curl build-essential make cmake libc6-dev gcc-7 g++-7 gcc-multilib
    - name: dependency (conda+pip+custom)
      run: |
        curl -sSL -o miniconda.sh \
          https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash miniconda.sh -b -p ${HOME}/opt/conda
        rm -rf miniconda.sh
        export PATH="${HOME}/opt/conda/bin:$PATH"
        hash -r
        conda config --set channel_priority strict
        conda update --all --yes
        conda install --yes pip python numpy scipy pytest pandas matplotlib mkl-include
        pip install nbgitpuller sphinx-gallery notebook jupyterlab rise cxxfilt
        pip install https://github.com/aldanor/ipybind/tarball/master
        export INSTALL_PREFIX=${INSTALL_PREFIX:-${HOME}/opt/conda}
        contrib/install.sh everything

    - name: Run pytest
      run: |
        make test
